### ISSUE TITLE
TypeError: s.logFailedRequest is not a function

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-java#2480]
Below error randomly occurs.

```
[2022-05-30 09:58:06.658] [exthost] [error] [redhat.java] provider FAILED
[2022-05-30 09:58:06.659] [exthost] [error] TypeError: s.logFailedRequest is not a function
	at c:\Users\admin\.vscode\extensions\redhat.java-1.6.6\dist\extension.js:2:697930
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async U.provideCodeActions (c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:103131)
[2022-05-30 09:58:07.727] [exthost] [error] [redhat.java] provider FAILED
[2022-05-30 09:58:07.727] [exthost] [error] TypeError: s.logFailedRequest is not a function
	at c:\Users\admin\.vscode\extensions\redhat.java-1.6.6\dist\extension.js:2:697930
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async U.provideCodeActions (c:\Users\admin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:103131)

```

Related code:

https://github.com/redhat-developer/vscode-java/blob/01d07b9aaa4ae3375a2927042708a62c856bc384/src/extension.ts#L310

`LanguageClient` has no method `logFailedRequest`, not sure why it's called here... and because client is declared as `any` type, it passes TS compilation. BTW, we should avoid using `any` type unless we have to, then such error would be guarded at early stage.

**Comment by rgrunber** [comment]
The method existed in older versions of the client. See https://github.com/microsoft/vscode-languageserver-node/commit/e5d7ad881b1a51b486e3f0e4aa0fbc25dad2be58 . Interestingly, this was introduced in https://github.com/redhat-developer/vscode-java/commit/78c82941606c1392f56b76491dc8aba87cd47faa , but even then, we were using a version of the language client that would have contained the new API, so maybe @snjeza was just testing with some older version.
