### ISSUE TITLE
will not show the errors in the enum class

### ISSUE THREAD

**Issue by tank59he** [redhat-developer/vscode-java#739]
Issue Type: <b>Bug</b>

public class Thee{
    public static void main(String[] args){
        System.out.println(Size1.SMALL);
    }
}
public enum Size1{      ### **//the second "public" this shoud be confirm as  a error**
    SMALL
    ,LARGE
}
//this will dont show the errors and will Compile and pass。But just print "null".Beacause compiler Ignore the wrong enum class.

Extension version: 0.35.0
VS Code version: Code 1.29.1 (bc24f98b5f70467bc689abf41cc5550ca637088e, 2018-11-15T19:13:36.375Z)
OS version: Windows_NT x64 10.0.17134

**Comment by yaohaizh** [comment]
@tank59he Is this a standalone file?

**Comment by tank59he** [comment]
no is not

**Comment by fbricon** [comment]
@tank59he is it part of a maven or gradle project? can you share your project?

**Comment by tank59he** [comment]
@fbricon like this
![image](https://user-images.githubusercontent.com/37946493/49740824-04e03600-fcd0-11e8-972c-660400669422.png)

**Comment by tank59he** [comment]
if there are some error in the enum class there will have not some error report. @fbricon

**Comment by fbricon** [comment]
Ok so this is a standalnone java file. You might have noticed the "Classpath is incomplete" [warning](https://github.com/redhat-developer/vscode-java/wiki/%22Classpath-is-incomplete%22-warning). There's no easy way to know if that file works on its own or is part of a bigger thing, so some compilation errors are disabled on purposed.

No, we've been working on improving the user experience in some cases, such as yours, so you should now see better feedback with the next version of vscode-java. You can try the [latest CI build](http://download.jboss.org/jbosstools/jdt.ls/staging/?C=M;O=D), see if it works better for you (See manual vsix installation [instructions](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)).

**Comment by tank59he** [comment]
@fbricon Thank you! I got that.
