### ISSUE TITLE
Eclipse annotation processing is broken in v1.49.0

### ISSUE THREAD

**Issue by ChrisTrenkamp** [redhat-developer/vscode-java#4278]
I have a multi-project Gradle project that uses the `eclipse` and the https://github.com/diffplug/goomph `apt` plugins.  The project is set up with the `eclipse` task to generate the `.classpath` and `.project` Eclipse files for each project.

Up to v1.48.0, this has worked.  In the v1.49.0 release, something broke the annotation processing.  I should see a bunch of generated builder objects in each subproject's `apt_generated` directories, but each project only has one generated builder object, if it has any generated sources at all.  It's as if the annotation processing stops at the first Java file.

I took a look at the diff between v1.47.0 and v1.49.0, and there doesn't seem to be any particular change that stands out to me that might have affected the annotation processing.  I'm not sure what to look for.

**Comment by fbricon** [comment]
Can you provide a sample project reproducing this issue?

**Comment by ChrisTrenkamp** [comment]
[vscode-buildship-annotation-processor-issue.zip](https://github.com/user-attachments/files/23914915/vscode-buildship-annotation-processor-issue.zip)

Here's a reproducer.  Run `./gradlew eclipse` to generate the Eclipse settings, and then open the project in VSCode with the Java extension pack running.

In v1.48, it works correctly.  The `.apt_generated` directory generates the builder classes and the language server finds all the class definitions.

Then upgrade the extension to v1.50, run `./gradlew clean cleanEclipse`, `./gradlew eclipse`, and clean the workspace.  Now the `.apt_generated` directory is empty.  I'm not sure if the annotation processor is not running, or if the generated classes are being placed elsewhere.

**Comment by jackrein** [comment]
I am also running into this issue. Using v1.48.0 works, but after upgrading to v1.49.0 or v1.50.0 I am seeing unresolved imports for generated classes.

**Comment by jackrein** [comment]
Coming back to this – it appears these are related
1. https://github.com/redhat-developer/vscode-java/issues/4286
2. https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4687

**Comment by fbricon** [comment]
you can try the latest vscode-java pre-release, that includes the fix for this annotation processing bug.
