### ISSUE TITLE
After upgrade from v0.77.0 to v0.78.0 can't debug tests

### ISSUE THREAD

**Issue by rubensa** [redhat-developer/vscode-java#1915]
After upgrade from v0.77.0 to v0.78.0 can't debug tests, only execute them

##### Environment
- Operating System: Linux
- JDK version: 11
- Visual Studio Code version: 1.55.2
- Java extension version: 0.78.0

##### Steps To Reproduce
1. Open a maven project with JUnit tests
2. Try run the test in debug mode

##### Current Result
An error message appears and the test can't be run

##### Expected Result
Test is run stopping at any break point

##### Additional Informations
I I downgrade to version 0.77.0 everything works as expected.

The error message in the log is: 
`java.lang.NoSuchMethodError: 'void org.eclipse.jdi.internal.connect.ConnectorImpl$StringArgumentImpl.<init>(org.eclipse.jdi.internal.connect.ConnectorImpl, java.lang.String, java.lang.String, java.lang.String, boolean)'`

**Comment by victor-k-lee** [comment]
Got the same issue, thank you for the workaround.

**Comment by ruhrieGD** [comment]
Similar issue here. Can't debug anything though. Additionally, the "java.format.settings.url" setting is no longer being respected on 0.78.0. Downgrading fixed it. I suspect these are related.

**Comment by rothfels** [comment]
Yep, same issue for our team. No issues on v0.77.0.

**Comment by fbricon** [comment]
This is a downstream issue, vscode-java-debug needs to be recompiled. See https://github.com/microsoft/vscode-java-debug/issues/995

**Comment by snjeza** [comment]
>  the "java.format.settings.url" setting is no longer being respected on 0.78.0

@ruhrieGD Could you show your  "java.format.settings.url" property?

**Comment by snjeza** [comment]
You may want to take a look at https://github.com/microsoft/vscode-java-debug/issues/995#issuecomment-829762880

**Comment by testforstephen** [comment]
Hi, I just released a hotfix release 0.33.1 for "Debugger for Java" extension. It will work with both vscode-java@0.77.0 and 0.78.0. Please have a try. thanks.
